console.log("group 1");
console.warn("message one");
console.warn("message two");
console.groupCollapsed();
console.log("child one");
console.warn("message one");
console.warn("message two");
console.groupCollapsed();
console.log("child two");
console.warn("message one");
console.warn("message two");
console.groupEnd();
console.log("group 2");
console.warn("message 1");
console.warn("message 2");