let m1 = document.getElementById("elzero");
let m2 = document.querySelector("#elzero");
let m3 = document.querySelector(".element");
let m4 = document.querySelectorAll(".element")[0];
let m5 = document.getElementsByClassName("element")[0];
let m6 = document.getElementsByTagName("div")[0];
// let m7 = document.querySelector('[name="js"]');
let m7 = document.querySelectorAll('[name="js"]')[0];
let m8 = document.querySelector('[id="elzero"]');
let m9 = document.querySelector('[class="element"]');
let m10 = document.querySelectorAll('[class="element"]')[0];
let m11 = document.querySelectorAll('div.element')[0];
let m12 = document.body.children[0];
let m13 = document.getElementById(m1.getAttribute("id"));
let m14 = document.getElementsByClassName(m1.getAttribute("class"))[0];
let m15 = document.children[0].children[2].children[0];